# .github/dependabot.yml (Updated - Option 1)

# Dependabot configuration for version updates

version: 2
updates:
  - package-ecosystem: "pip" # Package manager: Python pip
    directory: "/" # Location of requirements.txt (repository root)
    schedule:
      interval: "daily" # How often to check for updates
    allow:
      # Monitor only these specific direct dependencies:
      - dependency-name: "sd-mecha"    # The core merging library
        dependency-type: "direct"
      - dependency-name: "optuna"      # The optimization library
        dependency-type: "direct"
      - dependency-name: "bayesian-optimization"  # The optimization library
        dependency-type: "direct"
      - dependency-name: "hydra-core"  # The configuration library
        dependency-type: "direct"
      # Add other critical dependencies here if desired (e.g., "torch", "safetensors")
      # but be mindful that frequent updates might require careful testing.
    commit-message:
      # Prefix commit messages for pip updates
      prefix: "pip"
      include: "scope"