defaults:
  - cargo:
    - negeuler1 # needed
    - negeuler2 # needed
#    - negeuler3
#    - negeuler4
#    - noob5 # needed
#    - noob6 # needed
#    - negeuler5
#    - negeuler6
#    - negeuler7
#    - negeuler8 # needed
#    - noob1 # needed
    - noob7 # needed
#    - noob2 # needed
#    - noob3 # needed
#    - noob8 # needed
    - noob9 # hires
    - noob10b # hires
#    - noob10 # hires
#    - noob11 # 2048x2048

score_weight: 1.0

prompt: ""
negative_prompt: ""

n_iter: 1
batch_size: 1
steps: 28
cfg_scale: 8
width: 512
height: 512
sampler_name: Euler a
sampler_index: Euler a

seed: 218
subseed: -1
subseed_strength: 0
seed_resize_from_h: -1
seed_resize_from_w: -1

enable_hr: false
denoising_strength: 0.45
firstphase_width: 0
firstphase_height: 0
hr_scale: 2
hr_upscaler: "4x_fatal_Anime_500000_G"
hr_second_pass_steps: 0
hr_resize_x: 0
hr_resize_y: 0

styles: []

restore_faces: false
tiling: false

eta: 0
s_churn: 0
s_tmax: 0
s_tmin: 0
s_noise: 1

vpred_enabled: true
extension_name: "Forge2 extras"